# devcontainer-nodejs environment
FROM node:lts-slim AS devcontainer-nodejs
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update -y && \
	apt-get install -y --no-install-recommends git bzip2 procps ca-certificates && \
	update-ca-certificates && \
	apt-get clean && rm -rf /tmp/* /var/lib/apt/lists/*

USER node
ENV HOME=/home/node
ENV	NPM_CONFIG_PREFIX=$HOME/.npm-global \
	PATH=$PATH:$HOME/.npm-global/bin
WORKDIR $HOME

# install tooling
RUN npm install -g @haxtheweb/create yarn && \
	yarn global add web-component-analyzer && \
	# clean node.js caches
	npm cache clean --force && \
    yarn cache clean
CMD ["/bin/bash"]

# devcontainer-php environment
FROM base AS devcontainer-php
USER ubuntu
CMD ["/bin/bash"]