name: Publish HAXTheWeb images to ghcr.io
on: [push]

permissions:
  contents: read

jobs:
  build-and-push:
    if: github.repository_owner == 'haxtheweb'

    strategy:
      matrix:
        target: [
          devcontainer-nodejs
          ]

    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
      packages: write

    with:
      output: image
      push: true
      context: .
      file: ./images/Containerfile
      target: ${{ matrix.target }}
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository_owner }}/${{ matrix.target }}
      set-meta-labels: true
      meta-tags: |
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=sha,prefix=sha-
        type=raw,value=latest,enable={{is_default_branch}}
      cache: true
      cache-scope: ${{ matrix.target }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
